name: Bump Version and Push Tag
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.yml"
jobs:
    build:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0 # Don't use @master unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          WITH_V: true