name: Build and Push to Docker
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            brotherlogic/tasklister
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REPOSITORY_URL }}
          username: ${{ secrets.REPOSITORY_USER }}
          password: ${{ secrets.REPOSITORY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: "${{ secrets.REPOSITORY_URL }}/${{ steps.meta.outputs.tags }}"
          platforms: linux/arm64,linux/amd64